import { VideoProject } from "@/types/videos";

/**
 * EDIT THIS FILE whenever you want to add/update portfolio work.
 *
 * video_link accepts a normal YouTube URL or YouTube Shorts URL.
 * Keep project_images empty — this portfolio is intentionally image-free.
 */
export const allVideoProjects: VideoProject[] = [
  {
    id: "clean-edit-01",
    video_title: "Add Your Clean Edit",
    video_description:
      "Replace this entry with one of your strongest clean, professional edits.",
    tags: ["Clean Edit", "Professional Editing"],
    cover_image: "",
    publish_date: "2026-01-01",
    client_name: "Your Client",
    client_image: "",
    client_feedback: "",
    video_link: "",
    project_images: [],
    category: ["Clean Edits"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "captions-01",
    video_title: "Add Your Caption Edit",
    video_description:
      "Replace this entry with a caption-heavy Reel, Short, or talking-head edit.",
    tags: ["Captions", "Short Form"],
    cover_image: "",
    publish_date: "2026-01-01",
    client_name: "Your Client",
    client_image: "",
    client_feedback: "",
    video_link: "",
    project_images: [],
    category: ["Captions"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "CapCut Pro"],
  },
  {
    id: "ugc-ads-01",
    video_title: "Add Your UGC Ad",
    video_description:
      "Replace this entry with an AI UGC-style product advertisement.",
    tags: ["UGC Ads", "Product Video", "AI Video"],
    cover_image: "",
    publish_date: "2026-01-01",
    client_name: "Your Client",
    client_image: "",
    client_feedback: "",
    video_link: "",
    project_images: [],
    category: ["UGC Ads"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "AI Video Tools"],
  },
  {
    id: "faceless-01",
    video_title: "Add Your Faceless Video",
    video_description:
      "Replace this entry with a faceless YouTube, Reel, or Shorts project.",
    tags: ["Faceless", "Storytelling", "Retention"],
    cover_image: "",
    publish_date: "2026-01-01",
    client_name: "Your Client",
    client_image: "",
    client_feedback: "",
    video_link: "",
    project_images: [],
    category: ["Faceless"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "promo-01",
    video_title: "Add Your Promotional Video",
    video_description:
      "Replace this entry with a commercial, promotional, or product-focused edit.",
    tags: ["Promotional", "Commercial", "Product"],
    cover_image: "",
    publish_date: "2026-01-01",
    client_name: "Your Client",
    client_image: "",
    client_feedback: "",
    video_link: "",
    project_images: [],
    category: ["Promotional"],
    duration: "",
    software_used: ["Adobe Premiere Pro", "Adobe After Effects"],
  },
  {
    id: "motion-01",
    video_title: "Add Your Motion Graphics Edit",
    video_description:
      "Replace this entry with your strongest motion graphics or kinetic typography work.",
    tags: ["Motion Graphics", "Kinetic Typography"],
    cover_image: "",
    publish_date: "2026-01-01",
    client_name: "Your Client",
    client_image: "",
    client_feedback: "",
    video_link: "",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "",
    software_used: ["Adobe After Effects", "Adobe Premiere Pro"],
  },
  {
    id: "ai-video-01",
    video_title: "Add Your AI Video Project",
    video_description:
      "Replace this entry with an AI-assisted commercial, UGC, or creative video.",
    tags: ["AI Video", "Creative Production"],
    cover_image: "",
    publish_date: "2026-01-01",
    client_name: "Your Client",
    client_image: "",
    client_feedback: "",
    video_link: "",
    project_images: [],
    category: ["AI Video"],
    duration: "",
    software_used: ["AI Video Tools", "Adobe Premiere Pro"],
  },
];
